const LIGHT_PURPLE = '#F7F8FF'
const PURPLE = '#7381FF'
const LIGHT_GRAY = '#EBEBEB'
const GRAY = '#9A9A9A'
const RED = '#FF7373'
const LIGHT_GREEN = '#2BD75B'

export {
	LIGHT_PURPLE,
	PURPLE,
	LIGHT_GRAY,
	GRAY,
	RED,
	LIGHT_GREEN,
}